### ISSUE TITLE
Custom path for logs

### ISSUE THREAD

**Issue by Jeremy-FT** [lyra/plugin-prestashop#1]
Hi, it would be great if we can choose the path for the logs in the configuration page of the module. We want them to be at the root of the module for instance.

Thank you !

**Comment by frachedi** [comment]
Hi, thank you for your report, due to security reasons, we are not going to make this develop and because PrestaShop has already prepared path for logs: **/var/logs/** in newest versions and **/log/** or **/app/logs/** in older versions.

If despite, you wish to modify the path of logs, you just have to modify it in the function getLogger() int the /modules/lyra/classes/LyraTools.php file

Best regards !

**Comment by Jeremy-FT** [comment]
Ok I understand. Thank you !
